# Generated by Django 5.0.6 on 2024-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="TEST", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="TEST", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
