# Generated by Django 5.0.6 on 2024-12-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_auth",
            "0003_alter_customuser_email_alter_customuser_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={"ordering": ["email", "created_at"], "verbose_name_plural": "OTP"},
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(default="test@gmail.com", max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="otp",
            name="phone_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
