# Generated by Django 5.0.6 on 2024-12-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_alter_otp_options_otp_email_alter_otp_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to="profile_pictures/"),
        ),
    ]
