# Generated by Django 5.0.6 on 2024-12-15 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proj_manage", "0004_alter_buyingproperty_property_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectManagementService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("security", models.TextField(blank=True, null=True)),
                ("house_keeping", models.TextField(blank=True, null=True)),
                ("property_tax", models.TextField(blank=True, null=True)),
                ("electrical_and_repairs", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Management Services",
            },
        ),
    ]
