# Generated by Django 5.0.6 on 2024-12-26 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proj_manage", "0005_projectmanagementservice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="architecturedesign",
            options={
                "ordering": ["-date_created"],
                "verbose_name_plural": "Architecture and Design",
            },
        ),
        migrations.AlterModelOptions(
            name="buyingproperty",
            options={
                "ordering": ["-date_created"],
                "verbose_name_plural": "Buying Property",
            },
        ),
        migrations.AlterModelOptions(
            name="projectmanagementservice",
            options={
                "ordering": ["-date_created"],
                "verbose_name_plural": "Project Management Services",
            },
        ),
        migrations.AlterModelOptions(
            name="sellingproperty",
            options={
                "ordering": ["-date_created"],
                "verbose_name_plural": "Selling Property",
            },
        ),
        migrations.AlterModelOptions(
            name="swimmingpool",
            options={
                "ordering": ["-date_created"],
                "verbose_name_plural": "Swimming Pools",
            },
        ),
        migrations.AddField(
            model_name="architecturedesign",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyingproperty",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectmanagementservice",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellingproperty",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swimmingpool",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sellingproperty",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Land", "Land"),
                    ("Residential", "Residential"),
                    ("Commercial", "Commercial"),
                ],
                max_length=255,
            ),
        ),
    ]
