# Generated by Django 5.0.6 on 2024-12-26 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commercialproperty",
            options={
                "ordering": ["-date_created"],
                "verbose_name_plural": "Commercial Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="house",
            options={"ordering": ["-date_created"], "verbose_name_plural": "Houses"},
        ),
        migrations.AlterModelOptions(
            name="industrialproperty",
            options={
                "ordering": ["-date_created"],
                "verbose_name_plural": "Industrial Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="inquiries",
            options={"ordering": ["-date_created"], "verbose_name_plural": "Inquiries"},
        ),
        migrations.AddField(
            model_name="commercialproperty",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="industrialproperty",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inquiries",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
