# Generated by Django 5.0.6 on 2024-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_inquiries_alter_house_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialproperty",
            name="location",
            field=models.CharField(default="TEST", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="location",
            field=models.CharField(default="TEST", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="industrialproperty",
            name="location",
            field=models.CharField(default="TEST", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inquiries",
            name="report",
            field=models.TextField(default="TEST"),
            preserve_default=False,
        ),
    ]
