# Generated by Django 5.0.6 on 2024-12-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_commercialproperty_location_house_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiries",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("In Progress", "In Progress"),
                    ("Processed", "Processed"),
                ],
                default="Received",
                max_length=255,
            ),
        ),
    ]
